__This script generates the SimMod input data from the raw RCP data.__

In [14]:
import numpy as np
import pandas as pd

In [15]:
# Read RCP data
RCP_PATH = "../data/raw/RCP/"

rcp_emissions = dict()
rcp_concentrations = dict()
rcp_forcings = dict()

rcps = ['2.6', '4.5', '6.0', '8.5']
for rcp in rcps:
    if rcp == '2.6':
        name = '3PD'
    elif rcp == '4.5':
        name = '45'
    elif rcp == '6.0':
        name = '6'
    elif rcp == '8.5':
        name = '85'

    rcp_emissions[rcp] = pd.read_table(RCP_PATH+"RCP"+name+"_EMISSIONS.DAT",
                                       skiprows=37, sep='\s+')
    rcp_concentrations[rcp] = pd.read_table(RCP_PATH+"RCP"+name+"_MIDYEAR_CONCENTRATIONS.DAT",
                                            skiprows=38, sep='\s+')
    rcp_forcings[rcp] = pd.read_table(RCP_PATH+"RCP"+name+"_MIDYEAR_RADFORCING.DAT",
                                      skiprows=59, sep='\s+')

# -------------------------------
# Read original SimMod input data
SIMMOD_PATH = "../../SimMod/emissions/old_data/"

simmod_26_data = pd.read_csv(SIMMOD_PATH+"rcp_2.6_data.csv")
simmod_45_data = pd.read_csv(SIMMOD_PATH+"rcp_4.5_data.csv")
simmod_60_data = pd.read_csv(SIMMOD_PATH+"rcp_6.0_data.csv")
simmod_85_data = pd.read_csv(SIMMOD_PATH+"rcp_8.5_data.csv")
simmod_hist_ghgs = pd.read_csv(SIMMOD_PATH+"historical_ghgs.csv")

In [5]:
# N to N2O conversion factor
N_TO_N2O = (14.007*2+15.999)/(2*14.007)
N_TO_N2O

1.5711073034911116

In [16]:
# Create the SimMod input data
# ----------------------------------------------------------------------------------------
# RCP 2.6
temp_rcp_emissions_26 = rcp_emissions['2.6'].loc[:,['YEARS', 'CH4', 'N2O']]
temp_rcp_emissions_26.columns = ['year', 'ch4_emissions_tg', 'n2o_emissions_tg']
temp_rcp_emissions_26['c_emissions_pg'] = rcp_emissions['2.6']['FossilCO2'] + rcp_emissions['2.6']['OtherCO2']
temp_rcp_emissions_26['n2o_emissions_tg'] *= N_TO_N2O

temp_rcp_concentrations_26 = rcp_concentrations['2.6'].loc[:,['YEARS', 'CO2', 'CH4', 'N2O']]
temp_rcp_concentrations_26.columns = ['year', 'co2_concentration_ppm', 'ch4_concentration_ppb',
                                      'n2o_concentration_ppb']

temp_rcp_forcings_26 = rcp_forcings['2.6'].loc[:,['YEARS', 'CO2_RF', 'CH4_RF', 'N2O_RF', 'TOTAL_ANTHRO_RF']]
temp_rcp_forcings_26.columns = ['year', 'co2_forcing_wm2', 'ch4_forcing_wm2', 'n2o_forcing_wm2',
                                'total_forcing_wm2']

new_data_26 = pd.merge(temp_rcp_emissions_26, temp_rcp_concentrations_26, on='year')
new_data_26 = pd.merge(new_data_26, temp_rcp_forcings_26, on='year')

# ----------------------------------------------------------------------------------------
# RCP 4.5
temp_rcp_emissions_45 = rcp_emissions['4.5'].loc[:,['YEARS', 'CH4', 'N2O']]
temp_rcp_emissions_45.columns = ['year', 'ch4_emissions_tg', 'n2o_emissions_tg']
temp_rcp_emissions_45['c_emissions_pg'] = rcp_emissions['4.5']['FossilCO2'] + rcp_emissions['4.5']['OtherCO2']
temp_rcp_emissions_45['n2o_emissions_tg'] *= N_TO_N2O

temp_rcp_concentrations_45 = rcp_concentrations['4.5'].loc[:,['YEARS', 'CO2', 'CH4', 'N2O']]
temp_rcp_concentrations_45.columns = ['year', 'co2_concentration_ppm', 'ch4_concentration_ppb',
                                      'n2o_concentration_ppb']

temp_rcp_forcings_45 = rcp_forcings['4.5'].loc[:,['YEARS', 'CO2_RF', 'CH4_RF', 'N2O_RF', 'TOTAL_ANTHRO_RF']]
temp_rcp_forcings_45.columns = ['year', 'co2_forcing_wm2', 'ch4_forcing_wm2', 'n2o_forcing_wm2',
                                'total_forcing_wm2']

new_data_45 = pd.merge(temp_rcp_emissions_45, temp_rcp_concentrations_45, on='year')
new_data_45 = pd.merge(new_data_45, temp_rcp_forcings_45, on='year')

# ----------------------------------------------------------------------------------------
# RCP 6.0
temp_rcp_emissions_60 = rcp_emissions['6.0'].loc[:,['YEARS', 'CH4', 'N2O']]
temp_rcp_emissions_60.columns = ['year', 'ch4_emissions_tg', 'n2o_emissions_tg']
temp_rcp_emissions_60['c_emissions_pg'] = rcp_emissions['6.0']['FossilCO2'] + rcp_emissions['6.0']['OtherCO2']
temp_rcp_emissions_60['n2o_emissions_tg'] *= N_TO_N2O

temp_rcp_concentrations_60 = rcp_concentrations['6.0'].loc[:,['YEARS', 'CO2', 'CH4', 'N2O']]
temp_rcp_concentrations_60.columns = ['year', 'co2_concentration_ppm', 'ch4_concentration_ppb',
                                      'n2o_concentration_ppb']

temp_rcp_forcings_60 = rcp_forcings['6.0'].loc[:,['YEARS', 'CO2_RF', 'CH4_RF', 'N2O_RF', 'TOTAL_ANTHRO_RF']]
temp_rcp_forcings_60.columns = ['year', 'co2_forcing_wm2', 'ch4_forcing_wm2', 'n2o_forcing_wm2',
                                'total_forcing_wm2']

new_data_60 = pd.merge(temp_rcp_emissions_60, temp_rcp_concentrations_60, on='year')
new_data_60 = pd.merge(new_data_60, temp_rcp_forcings_60, on='year')

# ----------------------------------------------------------------------------------------
# RCP 8.5
temp_rcp_emissions_85 = rcp_emissions['8.5'].loc[:,['YEARS', 'CH4', 'N2O']]
temp_rcp_emissions_85.columns = ['year', 'ch4_emissions_tg', 'n2o_emissions_tg']
temp_rcp_emissions_85['c_emissions_pg'] = rcp_emissions['8.5']['FossilCO2'] + rcp_emissions['8.5']['OtherCO2']
temp_rcp_emissions_85['n2o_emissions_tg'] *= N_TO_N2O

temp_rcp_concentrations_85 = rcp_concentrations['8.5'].loc[:,['YEARS', 'CO2', 'CH4', 'N2O']]
temp_rcp_concentrations_85.columns = ['year', 'co2_concentration_ppm', 'ch4_concentration_ppb',
                                      'n2o_concentration_ppb']

temp_rcp_forcings_85 = rcp_forcings['8.5'].loc[:,['YEARS', 'CO2_RF', 'CH4_RF', 'N2O_RF', 'TOTAL_ANTHRO_RF']]
temp_rcp_forcings_85.columns = ['year', 'co2_forcing_wm2', 'ch4_forcing_wm2', 'n2o_forcing_wm2',
                                'total_forcing_wm2']

new_data_85 = pd.merge(temp_rcp_emissions_85, temp_rcp_concentrations_85, on='year')
new_data_85 = pd.merge(new_data_85, temp_rcp_forcings_85, on='year')

In [17]:
# Write data to csv
RCP_PREPROCESSED_PATH = "../data/preprocessed/"
#new_data_26.to_csv(RCP_PREPROCESSED_PATH+"rcp_2.6_data.csv")
#new_data_45.to_csv(RCP_PREPROCESSED_PATH+"rcp_4.5_data.csv")
#new_data_60.to_csv(RCP_PREPROCESSED_PATH+"rcp_6.0_data.csv")
#new_data_85.to_csv(RCP_PREPROCESSED_PATH+"rcp_8.5_data.csv")

In [10]:
new_data_85

,year,ch4_emissions_tg,n2o_emissions_tg,c_emissions_pg,co2_concentration_ppm,ch4_concentration_ppb,n2o_concentration_ppb,co2_forcing_wm2,ch4_forcing_wm2,n2o_forcing_wm2,total_forcing_wm2
0,1765,0.000000,0.000000,0.003000,278.05158,721.89411,272.95961,0.000000,0.000000,0.000000,0.000000
1,1766,1.963262,0.005191,0.008338,278.10615,722.25570,272.97121,0.011049,0.003576,0.000739,0.016319
2,1767,2.436448,0.010117,0.013677,278.22039,722.97082,272.99419,0.023246,0.007361,0.001516,0.033548
3,1768,2.911105,0.015043,0.019015,278.34305,723.66792,273.01678,0.025605,0.007773,0.001594,0.035170
4,1769,3.387278,0.019969,0.024353,278.47058,724.34313,273.03903,0.028057,0.008172,0.001670,0.036621
...,...,...,...,...,...,...,...,...,...,...,...
731,2496,922.990320,13.344000,1.495200,1961.57740,3481.18070,526.59945,10.476966,1.013923,0.727605,12.231577
732,2497,923.041410,13.344000,1.492550,1961.57740,3481.18070,526.59945,10.476966,1.013923,0.727605,12.231577
733,2498,923.092510,13.344000,1.489900,1961.57740,3481.18070,526.59945,10.476966,1.013923,0.727605,12.231577
734,2499,923.143600,13.344000,1.487250,1961.57740,3481.18070,526.59945,10.476966,1.013923,0.727605,12.231577
735,2500,923.194700,13.344000,1.484600,1961.57740,3481.18070,526.59945,10.476966,1.013923,0.727605,12.231577